spring.application.name=industrial-maintenance-api

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/maintenance_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Puerto
server.port=${PORT:8080}

# CORS
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}